class Category {
  final String title;
  final String image;

  Category({required this.title, required this.image});
}

class Texts {
  final String title;
  final String image;

  Texts({required this.title, required this.image});
}

final List<Category> categories = [
  Category(title: 'Durmuş', image: 'assets/popular/1.jpg'),
  Category(title: 'Maşgala', image: 'assets/popular/2.jpg'),
  Category(title: 'Öwüt-terbiýe', image: 'assets/popular/3.jpg'),
  Category(title: 'Ýaşlyk', image: 'assets/popular/4.jpg'),
  Category(title: 'Tebigat', image: 'assets/popular/5.jpg'),
  Category(title: 'Oboý obam', image: 'assets/popular/6.jpg'),
];

List<dynamic> carouselPages = [
  "assets/photo/1.jpg",
  "assets/photo/2.jpg",
  "assets/photo/3.jpg",
  "assets/photo/4.jpg",
  "assets/photo/5.jpg",
  "assets/photo/6.jpg",
];

final List<Texts> texts = [
  Texts(title: 'Bileýin  diýseň', image: 'assets/popular/1.jpg'),
  Texts(title: 'Öýkelemäň,  adamlar!', image: 'assets/popular/2.jpg'),
  Texts(title: 'Gerekdir', image: 'assets/popular/3.jpg'),
  Texts(title: 'Ýetmez  heý', image: 'assets/popular/4.jpg'),
  Texts(title: 'Oglum', image: 'assets/popular/5.jpg'),
  Texts(title: 'Ýaradandan  ýalňyz dileg', image: 'assets/popular/6.jpg'),
];

List<Map<String, dynamic>> poems = [
  {"id": 1, "title": "“Salam!” diýen eziz sözden"},
  {"id": 2, "title": "Aňlagyn"},
  {"id": 3, "title": "Arkadag  il"},
  {"id": 4, "title": "Awtobusyň şofýory"},
  {"id": 5, "title": "Aýly agşam"},
  {"id": 6, "title": "Aynekler"},
  {"id": 7, "title": "Bagşy sen"},
  {"id": 8, "title": "Bahar goşgusy"},
  {"id": 9, "title": "Bakylyk hakda oýlanma"},
  {"id": 10, "title": "Baradyr"},
  {"id": 11, "title": "Batyl"},
  {"id": 12, "title": "Beýiklik hakda tymsal"},
  {"id": 13, "title": "Beýiklik"},
  {"id": 14, "title": "Bir enäniň gyzyna igenji"},
  {"id": 15, "title": "Bizi saklasalar.."},
  {"id": 16, "title": "Bolmagyň gerek"},
  {"id": 17, "title": "Bolmawer"},
  {"id": 18, "title": "Bu-da geçer"},
  {"id": 19, "title": "Çaga oýny hakda"},
  {"id": 20, "title": "Çagalaryma pent"},
  {"id": 21, "title": "Çüw, atym!.."},
  {"id": 22, "title": "Dädemiň soňky sözlerinden"},
  {"id": 23, "title": "Dälmidir"},
  {"id": 24, "title": "Daň säher çagy"},
  {"id": 25, "title": "Deň-duşlaryň arasynda"},
  {"id": 26, "title": "Döredijilik pursatynda"},
  {"id": 27, "title": "Durmus"},
  {"id": 28, "title": "Düýş (degişme)"},
  {"id": 29, "title": "Duýup gez"},
  {"id": 30, "title": "Ekspromt"},
  {"id": 31, "title": "ene aladasy"},
  {"id": 32, "title": "eselme gownum"},
  {"id": 33, "title": "Futbol pökgüsi hakda tymsal"},
  {"id": 34, "title": "Futbol"},
  {"id": 35, "title": "Galplyk hakda oýlanma"},
  {"id": 36, "title": "Garagol Myrat"},
  {"id": 37, "title": "Garaş! "},
  {"id": 38, "title": "Garrylyk diýrler"},
  {"id": 39, "title": "Gelin gelýär!"},
  {"id": 40, "title": "Göribiň häsiýeti"},
  {"id": 41, "title": "Göwnüm seni"},
  {"id": 42, "title": "Göwnüm"},
  {"id": 43, "title": "Gowy adam boljak boldum"},
  {"id": 44, "title": "Gözel bar..."},
  {"id": 45, "title": "Gözler—ýürek aýnasy"},
  {"id": 46, "title": "Gurjak "},
  {"id": 47, "title": "Gyjakçy bilen kemakyl (halk ýumory)."},
  {"id": 48, "title": "Gyş aýdymjygy"},
  {"id": 49, "title": "Gyzlar toýa gelipdir"},
  {"id": 50, "title": "Hak sözi ýigrendik..."},
  {"id": 51, "title": "Hakykat (sonetler çemenine magistral)"},
  {"id": 52, "title": "Halallyk hakynda"},
  {"id": 53, "title": "Häsiýet"},
  {"id": 54, "title": "Il-gün"},
  {"id": 55, "title": "Inim hakda oýlanma"},
  {"id": 56, "title": "Käbäm enem, sen hakda"},
  {"id": 57, "title": "Kakam nirde bukuldy"},
  {"id": 58, "title": "Kate gynanyarlar"},
  {"id": 59, "title": "Kenardaky oýlanma"},
  {"id": 60, "title": "Kyn mesele (Ýetginjeklik ýatlamasy)."},
  {"id": 61, "title": "Mahrem ene"},
  {"id": 62, "title": "Matallar (2)"},
  {"id": 63, "title": "Matallar"},
  {"id": 64, "title": "Meşhur oglan"},
  {"id": 65, "title": "Meteor"},
  {"id": 66, "title": "Monjugatdy"},
  {"id": 67, "title": "Myradyň okaýşy"},
  {"id": 68, "title": "Myrat bilen güjügi"},
  {"id": 69, "title": "Netije"},
  {"id": 70, "title": "Nur bolsun"},
  {"id": 71, "title": "Nury aglasa..."},
  {"id": 72, "title": "Oglum"},
  {"id": 73, "title": "Ömür hakda oýlanma"},
  {"id": 74, "title": "Ömür kyssasy"},
  {"id": 75, "title": "Ömür menzili"},
  {"id": 76, "title": "Orazmyrat suratçy"},
  {"id": 77, "title": "Otuz ýaşda"},
  {"id": 78, "title": "Oylanmak"},
  {"id": 79, "title": "Öz häsiýetimden"},
  {"id": 80, "title": "Özüme on öwüt"},
  {"id": 81, "title": "Özüme öwüt"},
  {"id": 82, "title": "Özüňden gözle"},
  {"id": 83, "title": "Pişik-syçan oýnadylar..."},
  {"id": 84, "title": "Pyşdyl"},
  {"id": 85, "title": "Rubagylar  (2)"},
  {"id": 86, "title": "Rubagylar  (3)"},
  {"id": 87, "title": "Rubagylar  (4)"},
  {"id": 88, "title": "Rubagylar  (5)"},
  {"id": 89, "title": "Rubagylar "},
  {"id": 90, "title": "Rubagylar"},
  {"id": 91, "title": "Şahyr dostumyň hatyna jogap"},
  {"id": 92, "title": "Saňa"},
  {"id": 93, "title": "Seni göresim gelýär"},
  {"id": 94, "title": "şowsuz gun"},
  {"id": 95, "title": "Syçanjyk"},
  {"id": 96, "title": "Şygryýet bir dünýä"},
  {"id": 97, "title": "Synag"},
  {"id": 98, "title": "Täleý"},
  {"id": 99, "title": "Täsir "},
  {"id": 100, "title": "Tost"},
  {"id": 101, "title": "Tozgajyk"},
  {"id": 102, "title": "Uly menziliň oýlanmasy"},
  {"id": 103, "title": "Umyt"},
  {"id": 104, "title": "Ýagşy ynanç"},
  {"id": 105, "title": "Ýaş şahyr bilen bölüm müdiri"},
  {"id": 106, "title": "Ýaşlyk ahwaly"},
  {"id": 107, "title": "Ýatlamalar—ömür beýany"},
  {"id": 108, "title": "Ýekşenbe goşgusy"},
  {"id": 109, "title": "Ýene-de ynsap hakda"},
  {"id": 110, "title": "Ýetersiň"},
  {"id": 111, "title": "Ýetginjege"},
  {"id": 112, "title": "Ýetir"},
  {"id": 113, "title": "Ykbal meni şahyr etjek bolupdyr..."},
  {"id": 114, "title": "Ynsap"},
  {"id": 115, "title": "Ýolagçy"}
];

List<Map<String, dynamic>> favPoems = [];
